#!/bin/bash

set -ue
set -o pipefail

BASE_BRANCH=origin/master

latest_uncommited_satysfi_version () {
	git status --porcelain=v1 -- packages/satysfi/ | sed -e 's/^..\s*//' -e 's!.*/satysfi\.!!' -e 's!/.*!!' | tail -n 1
}

update_satysfi_version () {
	VERSION=$1
	shift
	sed -e '/^\s*"satysfi" {/s!"[-.+~0-9a-z]*"}!"'"$VERSION"'"}!' "$@"
}

show_help () {
	echo "Usage: $0 --opam <opam-file> [--satysfi <version>]"
}


OPAM_FILE=
SATYSFI_VERSION=
args=`getopt -o "" -l opam:,satysfi: -- "$@"`
if [ "$?" != 0 ]; then
	show_help 1>&2
	exit 1
fi
eval set -- "$args"
for OPT in "$@"
do
	case "$OPT" in
		--satysfi)
			SATYSFI_VERSION=$2
			shift 2
			;;
		--opam)
			OPAM_FILE=$2
			shift 2
			;;
		--)
			shift
			break
			;;
	esac
done

if [ -z "$OPAM_FILE" ] ; then
	show_help 1>&2
	exit 1
fi

if [ -z "$SATYSFI_VERSION" ] ; then
	SATYSFI_VERSION="$(latest_uncommited_satysfi_version)"
fi

temp_file=$(mktemp)
trap "rm -f $temp_file" 0 2 3 15


if [ -n "$VERSION" ] ; then
	update_satysfi_version "$SATYSFI_VERSION" "$OPAM_FILE" > "$temp_file"
else
	echo "No version specified"
fi

mv "$temp_file" "$OPAM_FILE"
